---
- name: Create directories for blob stores
  file:
    path: "{{ item['path'] }}"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    state: directory
    recurse: true
  when: item.path is defined
  loop: "{{ nexus_blobstores }}"

- name: Create/Check blobstores
  include_tasks: call_script.yml
  vars:
    script_name: create_blobstores_from_list
    args: "{{ nexus_blobstores }}"
  when: nexus_blobstores | length > 0
