---
- name: Создание группы Nexus
  group:
    name: "{{ nexus_os_group }}"
    state: present

- name: Создание пользователя Nexus
  user:
    name: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    shell: /bin/bash
    state: present
    system: yes 